name: snipes
version: '0'
base: core18
summary: Snipes
description: |
  The classic 1982 text-mode game Snipes, ported from the original DOS
  executable with 100% identical game logic, with replay recording added

grade: stable
confinement: strict

apps:
  snipes:
    command: launcher
    plugs:
      - home
      - network
      - network-bind
      - x11
      - opengl
      - pulseaudio

parts:
  integration:
    plugin: dump
    source: snap/local
  snipes:
    plugin: make
    source: .
    override-build: |
      make
      cp -a snipes $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - libsdl2-dev
      - libsdl2-ttf-dev
    stage-packages:
      - libogg-dev
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libpulse0
      - libflac8
      - libsdl2-ttf-2.0-0
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxss1
      - libasound2
      - libasyncns0
      - libfreetype6
      - libpng16-16
      - libsndfile1
      - libsndio6.1
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1-mesa
      - libxkbcommon0
      - libsdl2-2.0-0